<html>
<head>
<style>
body {
	margin-top:20px;
	margin-left: 15px;
	margin-right: 15px;
}
table {
	width: 100%;
	}
th {
	text-align: left;
}
th.class {
	width: 20%;
}
th.file {
	width: 45%;
}
th.line {
	width: 10%;
}
th.function {
	width: 25%;
}
</style>

<title>500 - Server Error</title>
</head>
<body>
<div class="body">
	<p><?php echo $message?></p>
	<hr />
	<?php echo $table ?>
</div>
</body>
</html>